config/routes.rb
Rails.application.routes.draw do 
  mount RailsAdmin::Engine => '/sadmin', as: 'rails_admin'
  devise_for :users 

  resources :books do 
    resources :reviews, except: [:show]
    resources :comments, except: [:index,:show]
  end

  root 'books#index'
  get 'books/:id/author', controller: 'books', action: 'show_author', as: 'show_author'

  mount ActionCable.server => '/cable'
end

app/models/ability.rb
# frozen_string_literal: true
class Ability
  include CanCan::Ability

  def initialize(user)      
    user ||= User.new
    if user.superadmin?
      can :manage, :all
      can :manage, :rails_admin
      can :manage, :dashboard
    end
    
    if user.admin_role?
      can :access, :rails_admin
      can :manage, :dashboard
      can :read, User
      can :destroy, User, { superadmin: false, admin_role: false }
      can :edit, User, { superadmin: false, admin_role: false }
      can :create, User
      can :manage, Book
      can :manage, Comment
      can :manage, Review
      can :manage, Author
    end

    if user.moderator_role?
      can :manage, User, { superadmin: false, admin_role: false, moderator_role?: false }
      can :manage, Book
      can :manage, Comment
      can :manage, Review
    end

    if user.user_role?
      can :read, Author
      can :read, Book
    end

    can :delete, Comment, user_id: user.id
    can :delete, Review, user_id: user.id

  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  has_attached_file :image, styles: { medium: '250x300>' }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
  has_many :books, dependent: :destroy
end

app/models/book.rb
class Book < ApplicationRecord
  

  scope :by_both, -> (search) { where("author_name LIKE ? OR title LIKE ?", "%#{search}%", "%#{search}%") }
   
  has_attached_file :image, styles: { medium: '250x300>' }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
  belongs_to :author
  has_many :reviews
  has_many :comments
end

app/models/comment.rb
class Comment < ApplicationRecord

  has_attached_file :image, styles: { medium: '250x300>' }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
  validates :body, presence: true, allow_blank: false

  belongs_to :parent, class_name: 'Comment', optional: true
  has_many :replies, class_name: 'Comment', foreign_key: :parent_id, dependent: :destroy
  
  belongs_to :user, optional: true
  belongs_to :book, optional: true
end

app/models/review.rb
class Review < ApplicationRecord
  validates :comment, presence: true, allow_blank: false
  validates :rating, presence: true, allow_blank: false
  belongs_to :user
  belongs_to :book
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :reviews, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_attached_file :avatar, styles: { medium: '100x100>', thumb: '59x59>' },
  default_url: '/assets/missing.png'
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/

  def username
    email.split('@').first
  end

  def self.current
    Thread.current[:user]
  end

  def self.current=(user)
    Thread.current[:user] = user
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!
  before_action :set_current_user

  def set_current_user
    User.current = current_user
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[email password_confirmation password avatar])
    devise_parameter_sanitizer.permit(:account_update, keys: %i[email password_confirmation password avatar])
  end
end

app/controllers/books_controller.rb
# Controller for books
class BooksController < ApplicationController
	include Pagy::Backend
	before_action :find_book, only: %i[show edit destroy update upvote add_author show_author]	
	skip_before_action :authenticate_user!, only: %i[index show show_author]
		
						
	def index  
		if params[:search]
     	@pagy, @books = pagy(Book.by_both(params[:search]), items: 3)
    else
			@pagy, @books = pagy(Book.all, items: 3)
    end
	end

	def show
		@comment = Comment.new
		@pagy, @comments = pagy(@book.comments.where(parent_id: nil).order('created_at DESC'), items: 10)
		@reviews = @book.reviews
				
		if @reviews.blank?
			@avg_review = 0
			@emptystars = 5
		else
			@avg_review = @reviews.average(:rating).floor
			@emptystars = 5 - @avg_review.to_i
		end
	end
		
	def new # for moderator only, admin and sadmin will use dashoboard to create
		unless user_signed_in? && current_user.moderator_role == true
			redirect_to root_path
		end
		@book = Book.new()
	end
		
	def create
		@book = Book.create(book_params)
		@author = Author.find_or_create_by(name: @book.author_name)
		@book.author = @author
		@book.save	
		redirect_to @book, notice: 'Successfully created book'
	end
									
	def edit; end

	def update
		if @book.update(book_params)
			redirect_to @book, notice: 'book was successfully updated'
		else
			render 'edit'
		end
	end
							
	def destroy
		@book.destroy
		redirect_to root_path
	end

	def show_author
		@author = @book.author
	end										
	
	private
	
		def book_params
			params.require(:book).permit(:title,:author_name,:image)
		end
							
	def find_book
		@book = Book.find(params[:id])
	end

end

app/controllers/comments_controller.rb
# Controller for comments
class CommentsController < ApplicationController
  before_action :set_comment, only: %i[show edit destroy update]
  before_action :set_book

  def new
    @comment = Comment.new
  end

  def edit; end

  def create
    @comment = @book.comments.new(comment_params)
    @comment.user = current_user
    @comment.save
    unless @comment.parent_id.nil?
      @reply = @comment
    end
    respond_to do |format|
      format.js { [@comment, @reply] }      
    end
  end

  def update
    if @comment.update(comment_params)
      redirect_to @book, notice: 'Comment was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @comment.destroy
    respond_to do |format|
      format.js { @comment }
    end
  end

  def set_comment
    @comment = Comment.find(params[:id])
  end

  private

  def comment_params
    params.require(:comment).permit(:body, :parent_id, :image)
  end

  def set_book
    @book = Book.find(params[:book_id])
  end

end

app/controllers/reviews_controller.rb
# Controller for reviews
class ReviewsController < ApplicationController
  include Pagy::Backend
  before_action :set_review, only: %i[show edit destroy update]
  before_action :set_book
  before_action :authenticate_user!

  def index
    @pagy, @reviews = pagy(@book.reviews, items: 5)
  end

  def new
    @review = Review.new
  end

  def edit; end

  def create
    @review = Review.new(review_params)
    @review.user = current_user
    @review.book = @book
    if @review.save
      redirect_to @book, notice: 'Review was successfully created.'
    else
      render :new
    end
  end

  def update
    if @review.update(review_params)
      redirect_to @book, notice: 'Review was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @review.destroy
    redirect_to reviews_url, notice: 'Review was successfully destroyed.'
  end

  private

  def set_review
    @review = Review.find(params[:id])
  end

  def set_book
    @book = Book.find(params[:book_id])
  end

  def review_params
    params.require(:review).permit(:rating, :comment)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
    include Pagy::Frontend    
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/books/_form.html.haml
= simple_form_for @book, html: {multiple: true} do |f|
        
    .form-group 
        =f.input :image, label: "Book Cover"

    .form-group 
        =f.input :title, input_html: {class: 'form-control' }, label: "Book Title"      

    .form-group
        %b Author Name 
        %br
        =f.collection_select :author_name, Author.order(:name),:name,:name, include_blank: true 
        %b * leave blank if specifying
        %br

    .form-group 
        =f.input :author_name, input_html: {class: 'form-control' }, label: "Specify if author doesn't already exist"
    
    %br
    .caption{:style => "text-align:center;"}
        = f.button :submit, class: "btn btn-primary"
    %br
        
        
                        

app/views/books/edit.html.haml
.col-md-7.col-md-offset-2
    %h1 Edit book
    = image_tag @book.image.url(:medium)
    = render 'form'
    = link_to 'Back', root_path

app/views/books/index.html.erb
<% if !user_signed_in? %>
<div class = "jumbotron">
    <h1> Your Favourite Books Reviewed! </h1>
    <p>IBDB is international books review site, 
    here you can find books of all genres and authors
     and give those books a review very easily.</p>
    <p><%= link_to "Sign up to write a review", new_user_registration_path, class: "btn btn-primary btn-lg"%></p>
    <p><%= link_to "Sign in", new_user_session_path, class: "btn btn-primary btn-lg"%></p>
</div>
<% end %>


<hr>
<% @books.each do |book|%>
    <div class = "col-sm-6 col-md-4">
        <div class = "thumbnail thumb-box" class="mimg"> 
            <h3  style = "text-align:center;" ><%= book.title%></h3>                
            <div class = "caption" style ="text-align:center;">                
                <%= link_to image_tag(book.image.url,size: "250x350"), book%><br>
                By <%= link_to book.author_name, show_author_path(book) %>                
            </div>
        </div>
    </div>
<%end%>

<div  style = "text-align:center;">
    <%= pagy_bootstrap_nav(@pagy).html_safe %>
</div>

app/views/books/new.html.haml
.col-md-8.col-md-offset-2
    .caption{:style => "text-align:center;"}
        %h1 New Book
        %br
        %br
    = render 'form'
    
    .caption{:style => "text-align:center;"}
        = link_to "Back", root_path, {class: 'my-class'}

app/views/books/show.html.erb
<div class = "row">
<div class = "col-sm-7 col-md-4">
  <h1 style ="text-align:center;"> Book </h1>
    <div class = "thumbnail thumb-box"> 
      <div class = "caption" style ="text-align:center;">
        <h1><%= @book.title%><br></h1>    
        <div style="padding-left:5px">        
        <%= image_tag(@book.image.url,size: "250x300")%><br><br>    
        </div>        
        <strong><p>By <%= link_to @book.author_name, show_author_path%></p><strong>
        <% @avg_review.to_i.times do  %>
          <span class="glyphicon glyphicon-star"></span>
        <% end %>
        <% @emptystars.to_i.times do  %>
          <span class="glyphicon glyphicon-star-empty"></span>
        <% end %>
        <p><b><%= pluralize(@book.reviews.count, "review") %></p>
        <% if can? :manage, Book %>
          <%= link_to "Delete", book_path(@book), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-default"%>
          <%= link_to "Edit", edit_book_path, class: "btn btn-default"%>
        <%end%>
        <% if user_signed_in? %>
          <% unless current_user.reviews.exists?(book_id: @book.id) %>
            <!-- Button trigger modal -->
            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
            Add Review
            </button>
            <!-- Modal -->
            <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
              <div class="modal-dialog" role="document">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Add review</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                  </div>
                  <div class="modal-body">
                    <%= form_for([@book, @review = Review.new]) do |form| %>  
                      <%= form.label :rating %>
                      <%= form.select(:rating, options_for_select([[1,1],[2,2],[3,3],[4,4],[5,5]])) %>    
                      <%= form.text_area(:comment, class: 'form-control', placeholder: "Tell us about the book" )%>
                      <div class="actions"><br/>
                        <%= form.submit('Submit review', class: 'btn btn-large btn-primary') %>
                      </div>
                    <% end %>
                  </div>
                  <div class="modal-footer">
                  </div>
                </div>
              </div>
            </div>
          <%end%>
        <%end%>
      </div>
    </div>
  </div>

<div class = "caption" style ="text-align:center;">
  <h1>Reviews </h1>
</div>
<div class = "col-md-7 col-md-offset-1">
  <% if @book.reviews.exists?%>
    <% @book.reviews.includes([:user]).limit(4).each do |review| %>
      <div class = "jumbotron jumbotron-fluid">
        <% review.rating.to_i.times do  %>
          <span class="glyphicon glyphicon-star"></span>
        <% end %>
        <% @empty = 5-review.rating %>
        <% @empty.times do  %>
          <span class="glyphicon glyphicon-star-empty"></span>
        <% end %>
        <br><br>
        <%= review.comment %> <br>
        Submitted by <%= review.user.email%>            
      </div>
    <% end %>
    <div class = "caption" style ="text-align:center;">
      <% if @book.reviews.count > 4%>
        <%= link_to "See more reviews", book_reviews_path(@book)%>
      <% end %>
    </div>
  </div>
  <% else %>
     This book has no review, add one if you like! 
  <%end%>
</div>
<br/>

<div class = "row">
  <div class = "caption" style ="text-align:center;">
    <h1><strong> Comments <strong> </h1>
    <% if current_user %>
      <%= render 'comments/form'%>
      <script> $(document).ready(roomReady); </script>
    <% else %>
      <h4>You need to <%= link_to "Sign In", new_user_session_path %> to comment </h4> <br>
      <% end %>
  </div>
  <div id="comment_pane" class="mycomment">
  
    <ol class="commentlist">
      <%= render(partial: 'comments/comment', collection: @comments.includes([:user])) %>
    </ol>
  </div>
  <div  style = "text-align:center;">
    <%= pagy_bootstrap_nav(@pagy).html_safe %>
</div>
</div>


<!-- Modal -->
<div id="replyModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="replyModalLabel1" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        <h5 style ="text-align:center;" class="modal-title" id="replyModalLabel1">REPLYING TO </h5><span id="parent_comment"></span>
        
      </div>
        <div class="modal-body">
        <input type="text" id="comment" class= 'form-control'>
        <% if user_signed_in?%>
          <input type="hidden" id="user_id" name="user_id" value="<%= current_user.id %>">
        <%end%>
        <input type="hidden" id="parent_id" name="parent_id">
                 
              
              
            <button class="btn btn-primary btn-large" onclick="saveReply(<%= @book.id %>)">Reply</button>
          </div>
        </div>
        </div>        
      </div>
    </div>
  </div>          
</div>

app/views/books/show_author.html.erb
<div class = "row">
	<div class = "col-sm-7 col-md-4">   
		<div class = "caption" style ="text-align:center;">
			<h1><%= @author.name %><br></h1><br/>			       
			<%= image_tag(@author.image.url,size: "300x350")%><br><br>				
		</div>
  </div>
	<div class = "caption" style ="text-align:center;">
		<h1>Description </h1>
	</div>
  <div class = "col-md-7 col-md-offset-1">    
    <div class = "jumbotron">         
      <%= @author.description %>            
    </div>
  </div>
</div>

<br/>
        
<div class = "row">
  <div class = "caption" style ="text-align:center;">
  	<h1>Books from this author</h1>
		<% @author.books.each do |book|%>
			<div class = "col-sm-6 col-md-4">
				<div class = "thumbnail thumb-box">
					<h2 style = "text-align:center;"><%=link_to book.title, book %></h2>
					<div class = "caption" style ="text-align:center;">
						<%= link_to image_tag(book.image.url,size: "250x300"), book%>
					</div>
				</div>
			</div>
    <%end%>
	</div>
</div>

app/views/comments/_comment.html.erb
<li> 
  <div class = "jumbotron" id="comment_<%= comment.id %>">
    <h3><%= image_tag(comment.user.avatar.url,size: "59x59")%><strong> <%= comment.user.username%> says <br> </h3> 
    <% if comment.image_file_name? %>
      <div style ="text-align:center;">
        <div class="img-fluid img-thumbnail"> 
          <%=image_tag(comment.image.url,size: "200x250") %>

        </div>
      </div> <br><br>
    <% end %> 
    <%= comment.body%><strong><br><br>
    <%= time_ago_in_words(comment.created_at) %> ago
    <% if can? :delete, comment %>
      <%= link_to "Delete", book_comment_path(@book, comment), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-outline-primary btn-sm", remote: true %>|
      <%= link_to "Edit", edit_book_comment_path(@book,comment), class: "btn btn-outline-primary btn-sm" %>| 
    <% end %>
      <!-- Button trigger modal --> 
    <% if current_user %>     
      <button class="btn btn-outline-primary btn-sm" onclick="openCommentModal(<%= comment.id %>, `<%= comment.body %>`,`<%= comment.user.username%>`)" data-toggle="modal">
      <a >  Reply </a>
      </button>       
    <% end %>

    <div id=<%= "container_replies#{comment.id}" -%>>      
      <ol class="commentlist">
        <%= render partial: 'comments/comment', collection: comment.replies.includes([:user]) %>
      </ol>    
    </div>      
  </div>
</li>

app/views/comments/_form.html.erb
<%= form_with model: [@book, @comment] do |f|%>

<%= f.text_area :body, placeholder: "Add a comment", class: 'form-control', id:'commentmessage' %>

<div style ="text-align:center;">
<div class="image-upload">
   <label for="file-input">
     <span class="glyphicon glyphicon-camera"></span>
   </label>

   <%= f.file_field :image, id:"file-input" %>
</div>

<%= f.submit "Comment", class: 'btn btn-primary'%>

</div>

<% end %>


<br>

app/views/comments/_reply.html.erb
<div class="reply" id="comment_<%= reply.id %>">
 <h3 ><%= image_tag(reply.user.avatar.url,size: "59x59")%> <strong><%= reply.user.username %> replied<strong></h3>
            <p><%= reply.body %><br></p>
            <%= time_ago_in_words(reply.created_at) %> ago
              <%if can? :delete, reply %>                
                <%= link_to "Delete", book_comment_path(@book, reply) , method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-outline-primary btn-sm", remote: true%> 
              <% end %> 
              </div>
              

app/views/comments/_replyform.html.erb
<%= form_for @comment, url: book_comments_path(book) do |f| %>
  <%= f.text_area(:body, class: 'form-control', placeholder: "Enter reply here" ) %>
  
<% if user_signed_in?%>
  <%= f.hidden_field :user_id, :value => current_user.id %>
  <%end%>
  
  <%= f.hidden_field :parent_id, :value => good_id %>
  <div class = 'create post'><br/>
  <div style ="text-align:center;">
    <%= f.submit('Post', class: 'btn btn-large btn-primary')  %>
    </div>
  </div>

<%end%>

app/views/comments/create.js.erb
<% if @comment.parent_id.nil? %>
    $('#comment_pane').prepend("<%= j render @comment %>");
    App.chat.speak('<%=@comment.id%>')
    $('#comment_<%= @comment.id %>').hide().fadeIn(1000);
    $('#commentmessage').val('');
    $('#file-input').val('');    
<% else %>
    $('#container_replies<%=@reply.parent_id%>').append("<%= j render 'comments/comment', comment: @reply %>");     
    $('#replyModal').modal('hide');
    $("#comment").val('');
<% end %>

app/views/comments/destroy.js.erb
$("#comment_<%= @comment.id%>").fadeOut(500,function() {   
});

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<div style ='text-align:center;'>
<%= link_to 'Back', @book %>
</div>

app/views/comments/new.html.erb
<%= form_for @comment, url: book_comments_path do |f| %>
  <%= f.text_area(:body, class: 'form-control', placeholder: "Enter reply here" ) %>
  <%= f.hidden_field :user_id, :value => current_user.id %>
  
  <%= f.hidden_field :parent_id, :value => params[:parent_id] %>
  <div class = 'create post'><br/>
  <div style ="text-align:center;">
    <%= f.submit('Post', class: 'btn btn-large btn-primary')  %>
    </div>
  </div>
<%end%>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "IBDB", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if user_signed_in? %>          
          <li><%= link_to "Account", edit_user_registration_path %></li>
          <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
          <% if can? :access, :dashboard %>
          <li><%= link_to "Admin Dashboard", rails_admin_path %></li>
          <%end%>
          <% if current_user.moderator_role? %>
          <li><%= link_to "Add Book", new_book_path %></li>
          <% end %>

        <% else %>        
          <li><%= link_to "Sign Up", new_user_registration_path, class: "active" %></li>
          <li><%= link_to "Sign In", new_user_session_path, class: "active" %></li>
        <% end %>
      </ul>
      
     <% if request.url == request.base_url || request.url == "http://localhost:3000/" || request.url == "http://localhost:3000/books" %>
      <form class= "navbar-form navbar-right"  role= "search">
        <div class = "form-group">            
            <%= form_tag books_path, :method => "get" do %>
					  <%= label_tag(:search, "") %>            
					  <%= text_field_tag :search, params[:search], placeholder: "Search by title or author" %>
          <button type ="submit" class = "btn btn-default"><span class="glyphicon glyphicon-search"> </span></button>
          <%end%>
            </div>
        
        </form>
    <% end %>    
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<%# 
<div class ="container">

      <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #e3f2fd;">
    <a class="navbar-brand" href="http://localhost:3000">IBDB</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor03" aria-controls="navbarColor03" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarColor03">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="http://localhost:3000/books/new">Add book <span class="sr-only">(current)</span></a>
       <li class="nav-item active">
          <a class="nav-link" href="http://localhost:3000/users/sign_in">Sign In <span class="sr-only">(current)</span></a>
          <li class="nav-item active">
          <a class="nav-link" href="http://localhost:3000/users/sign_up">Sign Up <span class="sr-only">(current)</span></a>
      </ul>
      <form class="form-inline">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-primary my-2 my-sm-0" type="submit">Search</button>
      </form>
    </div>
  </nav>
</div> %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Ibdb</title>    
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>   
  </head>
  <body>
<%= render 'layouts/header'%>
<div class = "container">
<p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
    <%= yield %>
    </div>
  </body>
</html>

app/views/reviews/_form.html.erb
<%= form_for(@book, @review) do |form| %>

  <% if review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :rating %>
    <%= form.select(:rating, options_for_select([[1,1],[2,2],[3,3],[4,4],[5,5]])) %>
  </div>

  <div class="field">
    <%= form.label :comment %>
    <%= form.text_area :comment %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/reviews/edit.html.erb
<h1>Editing Review</h1>

<%= render 'form', review: @review %>

<%= link_to 'Show', @review %> |
<%= link_to 'Back', reviews_path %>

app/views/reviews/index.html.erb
<div class = "caption" style ="text-align:center;">
  <h1>Reviews </h1>
</div>

<div class = "col-md-10 col-md-offset-1">
  <% @reviews.includes([:user]).each do |review|%>
    <div class = "jumbotron">
      <% review.rating.to_i.times do  %>
        <span class="glyphicon glyphicon-star"></span>
      <% end %>
      <% @empty = 5-review.rating %>
      <% @empty.times do  %>
        <span class="glyphicon glyphicon-star-empty"></span>
      <% end %>
      <br><br>
      <%= review.comment %> <br>
      Submitted by <%= review.user.email%>
      <% if can? :delete, review %>
        <%= link_to "Delete", book_comment_path(@book, review) , method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-outline-primary btn-sm"%> 
      <%end %>
            </div>
            
        <% end %>
        
        </div>

        <div  style = "text-align:center;">
    <%= pagy_bootstrap_nav(@pagy).html_safe %>
</div>

        

app/views/reviews/new.html.erb
<h1>New Review</h1>

<%= render 'form', review: @review %>

<%= link_to 'Back', @book %>